macro(use_package PACKAGE)
  find_package(${PACKAGE} REQUIRED)

  set(USEPKG_LINK_DIR ${${PACKAGE}_LINK_DIR} ${USEPKG_LINK_DIR})
  set(USEPKG_INCLUDE_DIR ${${PACKAGE}_INCLUDE_DIR} ${USEPKG_INCLUDE_DIR})
  set(USEPKG_LIBRARIES ${${PACKAGE}_LIBRARIES} ${USEPKG_LIBRARIES})
endmacro (use_package)
