# This action speaks a given text and returns a succeed after finished
string text # Text to speak
---
---
int32 IDLE= 0
int32 SPEAKING= 1
int32 FINISHED= 2

float32 STEPS= 3

float32 progress
string feedback

